import Quasicategory.Basic
import Quasicategory.InternalHom
import Mathlib.CategoryTheory.Adhesive
import Mathlib.CategoryTheory.MorphismProperty.FunctorCategory
import Mathlib.CategoryTheory.Types.Monomorphisms
import Quasicategory.TopCatModelCategory.SSet.Skeleton

universe w v u

namespace SSet

open CategoryTheory Simplicial MorphismProperty MonoidalCategory

/-- boundary inclusions are monomorphisms. -/
instance boundaryInclusion_mono (n : ℕ) : Mono (boundary n).ι := instMonoι ∂Δ[n]

/-- horn inclusions are monomorphisms. -/
instance hornInclusion_mono (n : ℕ) (i : Fin (n + 1)) : Mono (horn n i).ι := instMonoι Λ[n, i]

-- inner horn inclusions are monomorphisms
instance innerHornInclusion_mono ⦃n : ℕ⦄ ⦃i : Fin (n + 3)⦄ (_h0 : 0 < i) (_hn : i < Fin.last (n+2)) :
    monomorphisms SSet (horn (n + 2) i).ι := hornInclusion_mono _ _

open MonoidalCategory in
/-- B ⊗ ∂Δ[n] ⟶ B ⊗ Δ[n] is a monomorphism. Should be generalized. -/
instance boundaryInclusion_whisker_mono (B : SSet) (n : ℕ) : Mono (B ◁ (boundary n).ι) := by
  have : ∀ (k : SimplexCategoryᵒᵖ), Mono ((B ◁ (boundary n).ι).app k) := by
    intro k
    rw [mono_iff_injective]
    rintro ⟨b, x⟩ ⟨b', x'⟩ h
    apply Prod.ext_iff.1 at h
    apply Prod.ext
    · exact h.1
    · simp only [boundary, whiskerLeft_app_apply] at h ⊢
      apply (Set.injective_codRestrict Subtype.property).mp
      exact fun ⦃a₁ a₂⦄ a ↦ a
      exact h.2
  apply NatTrans.mono_of_mono_app

instance IsStableUnderCobaseChange.monomorphisms : IsStableUnderCobaseChange (monomorphisms SSet) := by
  refine ⟨?_⟩
  intro A B A' B' f s f' t P hf
  letI _ : Mono f := hf
  letI _ : Adhesive SSet := adhesive_functor
  exact Adhesive.mono_of_isPushout_of_mono_right P

instance IsStableUnderTransfiniteComposition.monomorphisms :
    IsStableUnderTransfiniteComposition.{u} (monomorphisms (SSet.{u})) where
  isStableUnderTransfiniteCompositionOfShape J _ _ _ _ := by
    change (MorphismProperty.monomorphisms (_ ⥤ _)).IsStableUnderTransfiniteCompositionOfShape _
    infer_instance

-- `0077` (a) monomorphisms are weakly saturated
instance monomorphisms.WeaklySaturated : WeaklySaturated.{u} (monomorphisms SSet.{u}) :=
  ⟨ IsStableUnderCobaseChange.monomorphisms,
    IsStableUnderRetracts.monomorphisms,
    IsStableUnderTransfiniteComposition.monomorphisms⟩

open modelCategoryQuillen in
/-- `0077` (b) monomorphisms are generated by boundary inclusions. -/
lemma mono_eq_bdryInclusions : monomorphisms SSet.{u} = WeaklySaturatedClassOf.{u} BoundaryInclusions := by
  apply le_antisymm
  · rw [← transfiniteCompositions_pushouts_coproducts.{u}, transfiniteCompositions_le_iff,
      pushouts_le_iff, coproducts_le_iff]
    convert le_WeaklySaturatedClassOf I
    apply le_antisymm
    all_goals exact fun _ _ _ ⟨n⟩ ↦ .mk n
  · refine minimalWeaklySaturated _ _ ?_ (by infer_instance)
    intro _ _ f hf
    cases hf
    exact monomorphisms.infer_property _

/-- `006Y` trivial Kan fibration iff rlp wrt all monomorphisms -/
lemma trivialKanFibration_eq_rlp_monomorphisms :
    trivialKanFibration = (monomorphisms SSet).rlp:= by
  ext X Y p
  refine ⟨?_, ?_⟩
  · intro h
    rw [class_rlp_iff_llp_morphism, mono_eq_bdryInclusions]
    intro _ _ i hi
    refine minimalWeaklySaturated (MorphismClass p).llp BoundaryInclusions ?_ (llp.WeaklySaturated _) i hi
    intro _ _ _ hf _ _ _ hg
    induction hg with | mk => exact h _ hf
  · intro h _ _ p hp
    induction hp
    exact h _ (boundaryInclusion_mono _)

/-- `006Z`(a), trivial Kan fibrations admit sections -/
noncomputable
def trivialKanFibration_section {X Y : SSet} (p : X ⟶ Y)
    (hp : trivialKanFibration p) : Y ⟶ X := by
  rw [trivialKanFibration_eq_rlp_monomorphisms] at hp
  have : (emptyIsInitial.to X) ≫ p = (emptyIsInitial.to Y) ≫ (𝟙 Y) :=
    Limits.IsInitial.hom_ext emptyIsInitial _ _
  exact ((hp _ (initial_mono Y emptyIsInitial)).sq_hasLift (CommSq.mk (this))).exists_lift.some.l

/-- the above map is a section -/
lemma trivialKanFibration_section_comp {X Y : SSet} (p : X ⟶ Y) (hp : trivialKanFibration p) :
    trivialKanFibration_section p hp ≫ p = 𝟙 Y := by
  rw [trivialKanFibration_eq_rlp_monomorphisms] at hp
  have : (emptyIsInitial.to X) ≫ p = (emptyIsInitial.to Y) ≫ (𝟙 Y) :=
    Limits.IsInitial.hom_ext emptyIsInitial _ _
  exact ((hp _ (initial_mono Y emptyIsInitial)).sq_hasLift (CommSq.mk (this))).exists_lift.some.fac_right

/-
/-- `050J` (1) -/
instance kanComplex_of_trivialKanFibration {X Y : SSet.{0}}
    (p : X ⟶ Y) (hp : trivialKanFibration p) :
    KanComplex X → KanComplex Y := by
  intro h
  constructor --no longer works because Kan complex definition is no longer simple to work with
  intro n i σ₀
  rw [trivialKanFibration_eq_rlp_monomorphisms.{w}] at hp
  dsimp [rlp] at hp
  have : (emptyIsInitial.to X) ≫ p = (emptyIsInitial.to Λ[n, i]) ≫ σ₀ :=
    Limits.IsInitial.hom_ext emptyIsInitial _ _
  have τ₀ := ((hp _ (initial_mono Λ[n, i] emptyIsInitial)).sq_hasLift (CommSq.mk (this))).exists_lift.some
  obtain ⟨τ, hτ⟩ := h.hornFilling τ₀.l
  use τ ≫ p
  rw [← Category.assoc, ← hτ, τ₀.fac_right]
-/

/-- `050J` (3) --/
instance quasicategory_of_trivialKanFibration {X Y : SSet.{0}}
    (p : X ⟶ Y) (hp : trivialKanFibration p) :
    Quasicategory X → Quasicategory Y := by
  intro h
  constructor
  intro n i σ₀ h0 hn
  rw [trivialKanFibration_eq_rlp_monomorphisms] at hp
  dsimp [rlp] at hp
  have : (emptyIsInitial.to X) ≫ p = (emptyIsInitial.to Λ[n + 2, i]) ≫ σ₀ :=
    Limits.IsInitial.hom_ext emptyIsInitial _ _
  have τ₀ := ((hp _ (initial_mono Λ[n + 2, i] emptyIsInitial)).sq_hasLift (CommSq.mk (this))).exists_lift.some
  obtain ⟨τ, hτ⟩ := h.hornFilling h0 hn τ₀.l
  use τ ≫ p
  rw [← Category.assoc, ← hτ, τ₀.fac_right]

/-- inner anodyne morphisms are monomorphisms -/
lemma innerAnodyne_mono : innerAnodyne ≤ monomorphisms SSet := by
  rw [innerAnodyne_eq]
  refine minimalWeaklySaturated (monomorphisms SSet) InnerHornInclusions ?_ monomorphisms.WeaklySaturated
  intro _ _ _ h
  induction h with | mk => exact hornInclusion_mono _ _

end SSet
