import Quasicategory.Basic
import Quasicategory.InternalHom
import Mathlib.CategoryTheory.Adhesive
import Mathlib.CategoryTheory.MorphismProperty.FunctorCategory
import Mathlib.CategoryTheory.Types.Monomorphisms
import Quasicategory.TopCatModelCategory.SSet.Skeleton
import Mathlib.AlgebraicTopology.SimplicialSet.CategoryWithFibrations

universe w v u

namespace SSet

open CategoryTheory Simplicial MorphismProperty MonoidalCategory

open MonoidalCategory in
/-- B ⊗ ∂Δ[n] ⟶ B ⊗ Δ[n] is a monomorphism. Should be generalized. -/
instance boundaryInclusion_whisker_mono (B : SSet) (n : ℕ) : Mono (B ◁ (boundary n).ι) := by
  have : ∀ (k : SimplexCategoryᵒᵖ), Mono ((B ◁ (boundary n).ι).app k) := by
    intro k
    rw [mono_iff_injective]
    rintro ⟨b, x⟩ ⟨b', x'⟩ h
    apply Prod.ext_iff.1 at h
    apply Prod.ext
    · exact h.1
    · simp only [boundary, whiskerLeft_app_apply] at h ⊢
      apply (Set.injective_codRestrict Subtype.property).mp
      exact fun ⦃a₁ a₂⦄ a ↦ a
      exact h.2
  apply NatTrans.mono_of_mono_app

instance IsStableUnderCobaseChange.monomorphisms : IsStableUnderCobaseChange (monomorphisms SSet) where
  of_isPushout {_ _ _ _ f _ _ _} P hf :=
    --intro A B A' B' f s f' t P hf
    letI _ : Mono f := hf
    letI _ : Adhesive SSet := adhesive_functor
    Adhesive.mono_of_isPushout_of_mono_right P

instance IsStableUnderTransfiniteComposition.monomorphisms :
    IsStableUnderTransfiniteComposition.{u} (monomorphisms SSet.{u}) where
  isStableUnderTransfiniteCompositionOfShape J _ _ _ _ := by
    change (MorphismProperty.monomorphisms (_ ⥤ _)).IsStableUnderTransfiniteCompositionOfShape _
    infer_instance

-- `0077` (a) monomorphisms are weakly saturated
instance monomorphisms.WeaklySaturated : WeaklySaturated.{u} (monomorphisms SSet.{u}) :=
  ⟨ IsStableUnderCobaseChange.monomorphisms,
    IsStableUnderRetracts.monomorphisms,
    by infer_instance,
    IsStableUnderTransfiniteComposition.monomorphisms⟩

open modelCategoryQuillen in
/-- `0077` (b) monomorphisms are generated by boundary inclusions. -/
lemma mono_eq_bdryInclusions : monomorphisms SSet.{u} = saturation.{u} bdryInclusions := by
  apply le_antisymm
  · rw [← transfiniteCompositions_pushouts_coproducts.{u}, transfiniteCompositions_le_iff,
      pushouts_le_iff, coproducts_le_iff]
    convert le_saturation I
    apply le_antisymm
    all_goals exact fun _ _ _ ⟨n⟩ ↦ .mk n
  · rw [← WeaklySaturated.le_iff]
    intro _ _ _ ⟨n⟩
    exact monomorphisms.infer_property _

/-- `006Y` trivial Kan fibration iff rlp wrt all monomorphisms -/
lemma trivialFibration_eq_rlp_monomorphisms :
    trivialFibration = (monomorphisms SSet).rlp:= by
  apply le_antisymm
  · intro _ _ _ h
    rw [morphism_rlp_iff, mono_eq_bdryInclusions, ← WeaklySaturated.le_iff]
    intro _ _ _ hf _ _ _ ⟨⟩
    exact h _ hf
  · apply antitone_rlp
    intro _ _ _ ⟨n⟩
    exact monomorphisms.infer_property _

/-- `006Z`(a), trivial Kan fibrations admit sections -/
noncomputable
def trivialFibration_section {X Y : SSet} (p : X ⟶ Y)
    (hp : trivialFibration p) : Y ⟶ X := by
  rw [trivialFibration_eq_rlp_monomorphisms] at hp
  have : (isInitialEmpty.to X) ≫ p = (isInitialEmpty.to Y) ≫ (𝟙 Y) :=
    Limits.IsInitial.hom_ext isInitialEmpty _ _
  exact ((hp _ (initial_mono Y isInitialEmpty)).sq_hasLift (CommSq.mk (this))).exists_lift.some.l

/-- `006Z`(a), trivial Kan fibrations are split epimorphisms -/
noncomputable
instance {X Y : SSet} (p : X ⟶ Y) (hp : trivialFibration p) : SplitEpi p where
  section_ := trivialFibration_section p hp
  id := by
    rw [trivialFibration_eq_rlp_monomorphisms] at hp
    exact ((hp _ (initial_mono Y isInitialEmpty)).sq_hasLift (CommSq.mk (isInitialEmpty.hom_ext _ _))).exists_lift.some.fac_right

namespace modelCategoryQuillen

/-- `050J` (1) -/
instance kanComplex_of_trivialFibration {X Y : SSet}
    (p : X ⟶ Y) (hp : trivialFibration p) :
    KanComplex X → KanComplex Y := by
  intro hX
  dsimp [KanComplex]
  rw [HomotopicalAlgebra.isFibrant_iff Y, modelCategoryQuillen.fibration_iff] --no longer works because Kan complex definition is no longer simple to work with
  rw [trivialFibration_eq_rlp_monomorphisms] at hp
  intro _ _ _ h
  dsimp [rlp] at hp
  obtain ⟨_, ⟨h, hw⟩⟩ := h
  simp at h
  obtain ⟨n, _, h⟩ := h
  have := h hw
  rw [ofHoms_iff] at this
  obtain ⟨i, hi⟩ := this
  rw [Arrow.hasLiftingProperty_iff, hi, ← Arrow.hasLiftingProperty_iff]
  constructor
  intro σ₀ g sq
  have : (isInitialEmpty.to X) ≫ p = (isInitialEmpty.to Λ[n + 1, i].toSSet) ≫ σ₀ := isInitialEmpty.hom_ext _ _
  have τ₀ := ((hp _ (initial_mono Λ[n + 1, i] isInitialEmpty)).sq_hasLift (CommSq.mk this)).exists_lift.some
  obtain ⟨τ, hτ⟩ := hX.hornFilling τ₀.l
  constructor
  constructor
  exact ⟨τ ≫ p, by rw [← Category.assoc, ← hτ, τ₀.fac_right], Limits.terminal.hom_ext _ _⟩

end modelCategoryQuillen

/-- `050J` (3) --/
instance quasicategory_of_trivialFibration {X Y : SSet}
    (p : X ⟶ Y) (hp : trivialFibration p) :
    Quasicategory X → Quasicategory Y := by
  intro h
  constructor
  intro n i σ₀ h0 hn
  rw [trivialFibration_eq_rlp_monomorphisms] at hp
  have : (isInitialEmpty.to X) ≫ p = (isInitialEmpty.to Λ[n + 2, i]) ≫ σ₀ :=
    isInitialEmpty.hom_ext _ _
  have τ₀ := ((hp _ (initial_mono Λ[n + 2, i] isInitialEmpty)).sq_hasLift (CommSq.mk (this))).exists_lift.some
  obtain ⟨τ, hτ⟩ := h.hornFilling h0 hn τ₀.l
  use τ ≫ p
  rw [← Category.assoc, ← hτ, τ₀.fac_right]

/-- inner anodyne morphisms are monomorphisms -/
lemma innerAnodyne_mono : innerAnodyne ≤ monomorphisms SSet := by
  rw [innerAnodyne_eq, ← WeaklySaturated.le_iff]
  intro _ _ _ ⟨_, _⟩
  exact monomorphisms.infer_property _

end SSet
